title: Martha's Vineyard Polar Bears Data Analysis
email: itsallnans@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploration of attendence and related data for the amazing MV polar bears
  group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  keithfma

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

